# Generated by Django 5.0.1 on 2024-02-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pan_number',
            field=models.TextField(blank=True, max_length=9),
        ),
    ]
