# Generated by Django 5.0.1 on 2024-02-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_seller_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
