# Generated by Django 5.0.1 on 2024-02-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_seller_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pan_number',
            field=models.TextField(max_length=10),
        ),
    ]
