# Generated by Django 5.0.1 on 2024-01-28 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productName', models.TextField(max_length=200)),
                ('shortDescription', models.TextField(blank=True, max_length=50, null=True)),
                ('productImg', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('category', models.TextField(max_length=200)),
                ('animalCategory', models.TextField(default='Dog', max_length=200)),
                ('featured', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
