# Generated by Django 5.0.1 on 2024-02-05 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productName', models.TextField()),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('productImgUrl', models.URLField(blank=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('category', models.TextField(max_length=200, null=True)),
                ('animalCategory', models.TextField(default='Dog', max_length=200)),
                ('featured', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sellerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
            ],
        ),
    ]
