# Generated by Django 5.0.1 on 2024-01-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
