# Generated by Django 5.0.1 on 2024-02-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sellerId',
            field=models.ForeignKey(default='4083bab5c2f44100a861b1387fb250a6', on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
            preserve_default=False,
        ),
    ]
