# Generated by Django 5.0.1 on 2024-02-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0002_products_sellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sellerId',
        ),
    ]
