# Generated by Django 5.0.1 on 2024-02-10 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0003_alter_products_sellerid'),
        ('users', '0004_alter_seller_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sellerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
    ]
