# Generated by Django 5.0.1 on 2024-02-03 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0003_remove_products_sellerid'),
        ('users', '0002_alter_seller_is_active_alter_seller_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sellerId',
            field=models.ForeignKey(default='5056e06863764b979f07c13b32fe2c87', on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
            preserve_default=False,
        ),
    ]
