# Generated by Django 5.0.1 on 2024-02-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0005_remove_products_sellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productImg',
        ),
    ]
