# Generated by Django 5.0.1 on 2024-02-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='discounted',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
