# Generated by Django 5.0.1 on 2024-02-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0006_remove_products_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productImgUrl',
            field=models.URLField(blank=True),
        ),
    ]
