# Generated by Django 5.0.1 on 2024-01-27 16:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0006_alter_products_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images'),
        ),
    ]
