# Generated by Django 5.0.1 on 2024-01-27 16:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0008_alter_products_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImg',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
    ]
