# Generated by Django 5.0.1 on 2024-01-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0012_alter_products_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImg',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
