# Generated by Django 5.0.1 on 2024-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierdata', '0013_alter_products_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImg',
            field=models.ImageField(default='default.png', upload_to='products'),
        ),
    ]
