# Generated by Django 5.0.1 on 2024-02-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_userimg_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userImg',
            field=models.ImageField(blank=True, default='images/user-default.png', null=True, upload_to='user-profiles'),
        ),
    ]
