# Generated by Django 5.0.1 on 2024-02-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pets',
        ),
    ]
