# Generated by Django 5.0.1 on 2024-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0004_pets_description_pets_owner_pets_petimgurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
