# Generated by Django 5.0.1 on 2024-02-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0005_pets_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='user_email',
            new_name='email',
        ),
    ]
