# Generated by Django 5.0.1 on 2024-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0006_rename_user_email_pets_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
