# Generated by Django 5.0.1 on 2024-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0007_pets_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
