# Generated by Django 5.0.1 on 2024-02-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0011_remove_pets_owner_pets_ownerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='ownerId',
            new_name='owner',
        ),
    ]
