# Generated by Django 5.0.1 on 2024-02-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0012_rename_ownerid_pets_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pets',
            name='medicalDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pets',
            name='vaccinated',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
