# Generated by Django 5.0.1 on 2024-02-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0013_pets_email_sent_pets_medicaldescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='animal',
            field=models.TextField(default=True, null=True),
        ),
    ]
