# Generated by Django 5.0.1 on 2024-02-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0014_pets_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='animal',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
