# Generated by Django 5.0.1 on 2024-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0015_alter_pets_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
