# Generated by Django 5.0.1 on 2024-02-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0017_petadoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadoption',
            name='petId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paws.pets'),
        ),
    ]
