# Generated by Django 5.0.1 on 2024-02-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0019_remove_petadoption_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='vaccinated',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
